### ISSUE TITLE
[Bug]: game crash when i lunch from miniecraft launcher

### ISSUE THREAD

**Issue by ryannewcomer** [TheIllusiveC4/CuriousElytra#100]
### Minecraft Version

1.20.1

### What happened?

i am on version 1.20.4. i used forge, whenever i launch minecraft, it crash.
![image](https://github.com/illusivesoulworks/elytraslot/assets/88273136/3c3a4dfb-42a7-4f79-b929-f76f0706f52a)
forge saide it got 8 mode loaded. then this happen

### How do you trigger this bug?

download these:
![image](https://github.com/illusivesoulworks/elytraslot/assets/88273136/4e99075b-5c7b-4e3e-94ab-fd3bb325f51a)
2, run minecraft
3, forge siad it load 8 mode
4, minecarft crash

### Loader

Forge

### Loader Version

Forge - 1.20.4-forge-49.0.27

### API Version

N/A

### Mod Version

elytraslot-forge-6.3.0+1.20.1

### Relevant Log Outputs

https://pastebin.com/S0XL9n62

**Comment by TheIllusiveC4** [comment]
The mod is not yet available for 1.20.4, please follow https://github.com/illusivesoulworks/elytraslot/issues/107 for updates.
