### ISSUE TITLE
[Bug]: where is the elytra slot?

### ISSUE THREAD

**Issue by ChangeOtaku** [TheIllusiveC4/CuriousElytra#103]
### Minecraft Version

1.19.2

### What happened?

dont know if i did something wrong, but i didnt find the elytra slot (im using Curios), so i used /curious list and didnt find it there either

![image](https://github.com/illusivesoulworks/elytraslot/assets/40974662/b71b9fe9-7041-40b4-991c-3bba2a217f39)

### How do you trigger this bug?

1. install
2. look for elytra slot

### Loader

Forge

### Loader Version

Forge - 43.3.0

### Mod Version

Elytra Slot 6.1.1+1.19.2

**Comment by TheIllusiveC4** [comment]
This mod makes the elytra use the `back` slot, which is listed 9th in your screenshot.
