### ISSUE TITLE
"Enderite", "Deeper and Darker" and "Better End"  Mod support

### ISSUE THREAD

**Issue by MrMcSiber** [TheIllusiveC4/CuriousElytra#105]
### What is the new feature or improvement?

All three of these mods add elytras that cant be used with the slot. Would love them to be added. And a 1.20.4 Version would be kinda tight.

**Comment by TheIllusiveC4** [comment]
I tested these mods and they seem to be supported already. They should be, at least. If this is not the case, then please list submit a bug report with the version numbers of all the mods involved as well as the names of the items so that I can take a deeper dive.
