### ISSUE TITLE
[Bug]: Elytra Slot does not appear

### ISSUE THREAD

**Issue by cutekitticat** [TheIllusiveC4/CuriousElytra#106]
### Minecraft Version

1.20.1

### What happened?

As it says in the title, elytra Slot does not appear in the curios menu

### How do you trigger this bug?

idk, i have a huge modpack

### Loader

Forge

### Loader Version

Forge 47.2.21

### Mod Version

6.3.0

**Comment by TheIllusiveC4** [comment]
Do you not get a Back slot that you can use for Elytras?

**Comment by frankoito** [comment]
I have the same problem, yes, you can use the elytras in other slot in curios and in the chestplate... but, for no reason, the slot for the elytras (the mod) is not there

**Comment by TheIllusiveC4** [comment]
For clarification, the Back slot _is_ the slot used for elytra in this mod (at least in Curios). There is no dedicated slot for only elytra.
