### ISSUE TITLE
[Bug]:  Game crashes when I try to put the elytra in its supposed slot

### ISSUE THREAD

**Issue by HixouLz** [TheIllusiveC4/CuriousElytra#108]
### Minecraft Version

1.20.1

### What happened?

The game crashes whenever I try to put it in the slot and after that every time you try to load your inventory u crash. (I'm using it on 1.20.4)

### How do you trigger this bug?

1.put the elytra in the slot
2.
3.
...

### Loader

Fabric

### Loader Version

0.15.7

### API Version

0.96.11

### Mod Version

elytraslot-fabric-6.3.0+1.20.1

### Relevant Log Outputs

crash report : https://mclo.gs/rOAWfp6

**Comment by Xandeath75** [comment]
https://modrinth.com/mod/elytra_trinket/version/1.0.5

**Comment by TheIllusiveC4** [comment]
The mod is not yet available for 1.20.4, please follow https://github.com/illusivesoulworks/elytraslot/issues/107 for updates.
