### ISSUE TITLE
[Bug]: Crash with Quark and EMI

### ISSUE THREAD

**Issue by SaltSouls** [TheIllusiveC4/CuriousElytra#109]
### Minecraft Version

1.20.1

### What happened?

When scrolling through EMI with Quark and this mod installed, the game crashes after hitting a certain page. This crash seems to be related to the Elytra item renderer and also a problem with a duplicate capability key `curios:item`. If I had to guess I would say that it is something specific to the duplicate capability key and not the actual renderer.

### How do you trigger this bug?

1. install quark and EMI with Elytra Slot
2. Load into game
3. Open EMI
4. Scroll through EMI
5. Crash
6. ???
7. Profit
...

### Loader

Forge

### Loader Version

Forge - 47.2.23

### API Version

N/A

### Mod Version

6.3.0+1.20.1

### Relevant Log Outputs

[latest.log](https://gist.github.com/SaltSouls/d80f745723519f861114c330463d18e3) | [debug.log](https://gist.github.com/SaltSouls/6363b364eeb96a2d695656a188c6ba2a)

**Comment by TheIllusiveC4** [comment]
This seems like an issue with multiple mods trying to add the same capability to the elytra. Do you have any other elytra mods? Please try this with just Elytra Slot, it dependencies, and EMI and Quark installed and try to reproduce this issue. If it's not reproducible, then the culprit is likely a mod conflict with another mod in your list.

**Comment by SaltSouls** [comment]
> This seems like an issue with multiple mods trying to add the same capability to the elytra. Do you have any other elytra mods? Please try this with just Elytra Slot, it dependencies, and EMI and Quark installed and try to reproduce this issue. If it's not reproducible, then the culprit is likely a mod conflict with another mod in your list.

Hmmm... It would seem you are correct, though I'm not sure what would be adding the same capability to it... I will test more and get back to you when I find the proper culprit.

**Comment by SaltSouls** [comment]
I think I found the true culprit. It would seem like Beans Backpacks is trying to register the same slot as Elytra Slot. I will report this issue to them so that they can possibly fix it as this seems more like an issue on their end than with Elytra Slot.
