### ISSUE TITLE
[FORGE]Elytra Not Rendering as Enchanted When in Curio Slot.

### ISSUE THREAD

**Issue by Inpaladin** [TheIllusiveC4/CuriousElytra#11]
#### Versions:
* Curious Elytra: 4.0.0.1
* Caelus: 2.0.0.3
* Curios: 4.0.2.0
* Forge/Fabric: Forge 34.1.25
#### Observed Behavior: 
Elytra not appearing as enchanted on the player's back when in curio slot.
#### Expected Behavior: 
Elyrta shows as enchanted on the player's back.
#### Steps to Reproduce:
Enchant an Elytra and equip it.
#### Screenshots:
![image](https://user-images.githubusercontent.com/59532097/97260355-06d71380-17da-11eb-9049-043dc056d9ab.png)
![image](https://user-images.githubusercontent.com/59532097/97260378-1191a880-17da-11eb-96a8-0a166cfb633f.png)
![image](https://user-images.githubusercontent.com/59532097/97260393-19e9e380-17da-11eb-98f4-d4791140a6bc.png)
![image](https://user-images.githubusercontent.com/59532097/97260408-22dab500-17da-11eb-9aa8-2fd8ed8c1c40.png)

**Comment by TheIllusiveC4** [comment]
Fixed in Caelus 2.1.0.2.
