### ISSUE TITLE
[Bug]: Minecraft Java 1.20.4 Elytra Slot Mod not working

### ISSUE THREAD

**Issue by JFig7734** [TheIllusiveC4/CuriousElytra#110]
### Minecraft Version

1.20.1

### What happened?

Greetings everyone,
I am new to Minecraft and all of its mods. I have recently been told by a friend that I play with on his server to get this Mod for the Elytra. We are currently using Java 1.20.4 version. I have downloaded the ElytraSlot mod from Modrinth as well as trinkets-3.8.1, curious API , and Trinkets API. What is happening is when I put on all my armor, the selector button on the character skin screen does not appear and I have no way of accessing the back slot to put the Elytra on while in full armor/gear. Rather confused. Has anyone else had this happen? If so, does a fix exist? 
Thank you!

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Fabric

### Loader Version

Fabric - 1.20.4

### API Version

Fabric-api-0.96.11

### Mod Version

elytraslot-fabric-6.3.0+1.20.1

**Comment by TheIllusiveC4** [comment]
The mod is not yet available for 1.20.4, please follow https://github.com/illusivesoulworks/elytraslot/issues/107 for updates.
