### ISSUE TITLE
[Bug]: Wearing Elytra doesn't hide the cape.

### ISSUE THREAD

**Issue by soepie7** [TheIllusiveC4/CuriousElytra#111]
### Minecraft Version

1.20.1

### What happened?

Unlike what happens in vanilla, wearing a pair of elytra in the curio slot doesn't hide the cape. Disabling the cape in skin settings fixes it, but also reverts the cape to its capeless grey look.

### How do you trigger this bug?

1. Have cape enabled.
2. Wear elytra in curio slot.
3. Run or fall, so the cape moves (otherwise it is hidden under the elytra)

### Loader

Forge

### Loader Version

Forge 47.2.32

### Mod Version

6.3.0+1.20.1

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, when wearing the elytra in the curio slot the cape is hidden and the elytra changes texture as expected.  Please try and test this with only Curios, Caelus, and Elytra Slot and see if the issue persists. If it does not, it is most likely a mod conflict and you'll need to identify the mod that is causing the issue. Do you have any mods that add or modify capes?

**Comment by soepie7** [comment]
You're right, I forgot to account for other mods. The mod [Wavey Capes](https://modrinth.com/mod/wavey-capes) is the cause of this issue. I can confirm that that mod doesn't do it when equipping elytra normally, so it is specifically the mod interaction.
