### ISSUE TITLE
[Bug]: elytra uneuips when starting game

### ISSUE THREAD

**Issue by tenshiiclone** [TheIllusiveC4/CuriousElytra#113]
### Minecraft Version

1.20.1

### What happened?

every time i quit my save and then load it again my elytra unequips from the curio slot and goes into my inventory or on the ground if inventory is full. happens when game is completely quit and when going back to the title screen and loading again

### How do you trigger this bug?

1. load into minecraft singleplayer save
2. elytra unequips from curio slot
3.
...

### Loader

Forge

### Loader Version

47.2.32

### Mod Version

6.3.0 1.20.1

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this issue. I am able to exit and enter worlds without the elytra unequipping. Please try and test this with _only_ Curios, Caelus, and Elytra Slot and see if the issue persists. If it does not, it is most likely a mod conflict and you'll need to identify the mod that is causing the issue.

**Comment by tenshiiclone** [comment]
> I cannot reproduce this issue. I am able to exit and enter worlds without the elytra unequipping. Please try and test this with _only_ Curios, Caelus, and Elytra Slot and see if the issue persists. If it does not, it is most likely a mod conflict and you'll need to identify the mod that is causing the issue.

youre right. should have figured it was mod conflicts i just cant imagine what is doing it. thank you.
