### ISSUE TITLE
[Bug]: Cape no-clipping when used with the Wavey Capes mod

### ISSUE THREAD

**Issue by ArduFish** [TheIllusiveC4/CuriousElytra#114]
### Minecraft Version

1.20.6

### What happened?

When I use this mod with the Wavey Capes mod, sometimes the cape no-clips through the elytra while walking.
![339073031-ab5f3388-b22b-4999-9813-32129b7523be](https://github.com/illusivesoulworks/elytraslot/assets/80416599/a0cf3fbe-bd38-43f9-a6ee-dac394a931c4)

### How do you trigger this bug?

1. Get the Wavey Capes mod
2. Put an elytra in the elytra slot
3. Walk and jump in third person view

### Loader

Fabric

### Loader Version

0.15.11

### Mod Version

elytraslot-fabric-8.0.0+1.20.6

**Comment by TheIllusiveC4** [comment]
The cape shouldn't be showing at all. Are you using any other cape-related mods? Can you try testing with _only_ Wavey Capes and Elytra Slot (and its dependencies) installed? On my end, the cape isn't showing in my testing.

**Comment by ArduFish** [comment]
You have to walk and/or jump to see the cape.

**Comment by TheIllusiveC4** [comment]
Yes, I've done both as well as looked at every angle. The cape does not show in my testing. Are you using any other cape-related mods? Can you try testing with only Wavey Capes and Elytra Slot (and its dependencies) installed?

**Comment by ArduFish** [comment]
No, I am also using Elytra Physics, Fresh Moves, Not Enough Animations and Elytra Trims.

**Comment by ArduFish** [comment]
Issue does not appear anymore.
