### ISSUE TITLE
[missing upload] 1.20.2

### ISSUE THREAD

**Issue by Studiotaco** [TheIllusiveC4/CuriousElytra#115]
### Minecraft Version

1.20.4

### What happened?

im new to minecraft and i wanted a little help

~i use forge

### How do you trigger this bug?

1.e
2.
3.
...

### Loader

Forge

### Loader Version

1.20.2

### Mod Version

e

**Comment by TheIllusiveC4** [comment]
There are no plans for a 1.20.2 version on Forge.
