### ISSUE TITLE
Doesn't work with tinker's elytras

### ISSUE THREAD

**Issue by Vic-PT** [TheIllusiveC4/CuriousElytra#116]
### Minecraft Version

1.19.2

### What happened?

The slimelytras from Tinker's Construct are not equipable in the back curios slot

### How do you trigger this bug?

1. Obtain a slimytra
2. Try (and fail) to equip it in the back slot

### Loader

Forge

### Loader Version

Forge - 43.3.0

### Mod Version

6.1.2+1.19.2

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/illusivesoulworks/elytraslot/issues/43
