### ISSUE TITLE
[Feature]: Version 1.21 accessory mode scheduled for release?

### ISSUE THREAD

**Issue by pil0lo** [TheIllusiveC4/CuriousElytra#118]
### What is the new feature or improvement?

Will you also make version 1.21?
There is no accessory mode compatible with version 1.21 yet.

**Comment by vico93** [comment]
Trinkets [just had a release for 1.21](https://modrinth.com/mod/trinkets/version/3.10.0). I wonder if @TheIllusiveC4 will update this and Shulker Box Slot to 1.21 as well...

**Comment by TheIllusiveC4** [comment]
Yes, this will be updated to 1.21.

**Comment by pil0lo** [comment]
Thank you for the update.

**Comment by kidzkece** [comment]
Trinkets has been updated to version 1.21, will this mod also be updated to version 1.21?
