### ISSUE TITLE
[Bug]: Elytra Doesn't deplete durability

### ISSUE THREAD

**Issue by TheDiamondSquidy** [TheIllusiveC4/CuriousElytra#119]
### Minecraft Version

1.20.4

### What happened?

does not deplete durability

### How do you trigger this bug?

1. Use eltrya in back trinkets slot
2. Use rockets
3.
...

### Loader

Fabric

### Loader Version

fabric 0.15.11

### API Version

fabric APIf 0.97.1+1.20.4

### Mod Version

Elytra Slot 7.0+1.20.4

**Comment by TheIllusiveC4** [comment]
Is using a rocket a necessary step or does it not deplete durability regardless? And have you tested this with only Elytra Slot + Trinkets installed?

**Comment by TheDiamondSquidy** [comment]
Hi, Ive uploaded a video demonstrating the elytra with all 3 rocket types both in the regular slot and the elytra slot. 

Ive only used the trinkets API and the elytra slots mod for testing.

https://github.com/illusivesoulworks/elytraslot/assets/43652747/2c09d466-bb52-4ad3-9e61-c5dbe9b85429

In the video you can see:
1. Elytra functions normally in the chestplate slot.
2. Elytra (in the elytra slot) does not deplete durability whether using rockets or not. This applies to all rocket durations.

**Comment by Fyoncle** [comment]
I experience the same issue in 1.20.1 with Elytra Slot 6.4.0

**Comment by Fyoncle** [comment]
Tested with only Elytra Slot & Trinkets, still broken on 1.20.1 no matter what, also rocket is not a important step, just use ur elytra and see durability doesn't deplete

**Comment by TheDiamondSquidy** [comment]
Thanks for fixing!! really appreciate
