### ISSUE TITLE
Add 1.16.4 tag to CurseForge download of latest version

### ISSUE THREAD

**Issue by ZornTaov** [TheIllusiveC4/CuriousElytra#12]
Most 1.16.3 mods should work without any changes in 1.16.4, but using the Twitch launcher (now CurseForge launcher) won't let you download a mod to a pack if the mod doesn't have matching version tag. I tested the mod by copying in the jar file into a pack, and I didn't notice any changes that would break the general use of the mod.

**Comment by TheIllusiveC4** [comment]
Alright, done.
