### ISSUE TITLE
[Bug]: dont work

### ISSUE THREAD

**Issue by boogagatheman** [TheIllusiveC4/CuriousElytra#120]
### Minecraft Version

1.20.4

### What happened?

the elytra do not work when i equied it

### How do you trigger this bug?

1.euqid the elytra
2.try to fly 
3.dont work
...

### Loader

Fabric

### Loader Version

0.15.11 fabric

### API Version

Fabric API 0.97.1

### Mod Version

elytra slot 7.0.0

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, the elytra works fine in the Trinkets slot when I equip it. Have you tested this with only Elytra Slot and Trinkets installed?

**Comment by boogagatheman** [comment]
yes but it still not working

**Comment by TheIllusiveC4** [comment]
Can you share your `latest.log` or `debug.log` from the session?

**Comment by boogagatheman** [comment]
[latest.log](https://github.com/user-attachments/files/16261375/latest.log)
where to find the debug.log?

**Comment by TheIllusiveC4** [comment]
Was that your most recent session or the one where you tested this? That session doesn't have Elytra Slot or Trinkets loaded. Reproduce this behavior and then send the relevant `latest.log`.

**Comment by masuteri** [comment]
I've had this issue a long time ago as well and I believe it has the same cause. Another mod is causing the issue but I don't know which one as the pack I made is long gone already.

**Comment by Medatur76** [comment]
Hello! I saw in your log you have ViaFabricPlus and when I got rid of it that fixed my problem, leme know if it works for you :)
