### ISSUE TITLE
[Bug]:Game is not launching with elytra slot and customizable elytra.

### ISSUE THREAD

**Issue by SxRHunter** [TheIllusiveC4/CuriousElytra#121]
### Minecraft Version

1.21.0

### What happened?

The game doesn't even get to the main menu and it crashes.

### How do you trigger this bug?

1.Install fabric 1.21.
2.Install both elytra slot and customizable elytra.
3.launch the game.
...

### Loader

Fabric

### Loader Version

fabric 0.15.11

### API Version

Fabric API 0.100.7

### Mod Version

Elytra slot 9.0.0 +1.21 and customizable elytra 2.2.4+1.21

### Relevant Log Outputs

https://gist.github.com/SxRHunter/2a8e517de8980a3e6d0424a926beb8ba
Thank you.

**Comment by TheIllusiveC4** [comment]
This is a Customizable Elytra issue, they have a mixin into Elytra Slot that is outdated in 1.21.

**Comment by SxRHunter** [comment]
Thank you, i reported it to both mod makers to see which one has the issue.
Appreciate the work
