### ISSUE TITLE
[Bug]: encountered an error while dispatching

### ISSUE THREAD

**Issue by IllustrativeJackal** [TheIllusiveC4/CuriousElytra#123]
### Minecraft Version

1.21.0

### What happened?

The game encountered an error while i was starting up the game

### How do you trigger this bug?

1.open minecraft
2.look in disappointment
3.
...

### Loader

Forge

### Loader Version

neoforge 21.0.133

### API Version

N/A

### Mod Version

9.0.0

### Relevant Log Outputs

[crash-2024-07-24_21.24.00-fml.txt](https://github.com/user-attachments/files/16361525/crash-2024-07-24_21.24.00-fml.txt)

**Comment by TheIllusiveC4** [comment]
This is a mixin crash from Customizable Elytra, which is resolved by their latest update.
