### ISSUE TITLE
[Bug]: Game crashes when elytra is equipped (Fabric 1.20.2)

### ISSUE THREAD

**Issue by Coury96** [TheIllusiveC4/CuriousElytra#125]
### Minecraft Version

1.20.2

### What happened?

When I try to equip elytras the game automatically closes. I have Trinkets 3.8.0 on my mods folder, so I don't know why this always happens. Curseforge mod page says it is compatible with 1.20.2. I tried having only Trinkets and this mod in the folder and doesn't work.

### How do you trigger this bug?

1. Shift + Right click on elytra (Also equipping manually by dragging and drop it over the Trinkets slot)

### Loader

Fabric

### Loader Version

0.15.10

### API Version

0.91.6

### Mod Version

6.3.0

**Comment by TheIllusiveC4** [comment]
Apologies, it seems that I marked it as 1.20.2-compatible erroneously on the project page. Elytra Slot is not compatible with 1.20.2.
