### ISSUE TITLE
[Bug]: Specific Mixin Squared max version requirement breaks with other mods

### ISSUE THREAD

**Issue by brisingraerowing** [TheIllusiveC4/CuriousElytra#126]
### Minecraft Version

1.20.1

### What happened?

Game crashes on startup with mods like VS Additions.

Ref: xiewuzhiying/VS-Addition#16

### How do you trigger this bug?

1. Install this mod, VS Additions, and dependencies
2. Start Game
3. Crash

### Loader

Forge

### Loader Version

Forge 47.3.4

### API Version

N/A

### Mod Version

Elytra Slot 6.4.2+1.20.1

### Relevant Log Outputs

[Game output](https://gist.github.com/brisingraerowing/f24c863e6a022b11759b1df374aaaa70)

**Comment by TheIllusiveC4** [comment]
Hm, I can't help but feel like I made the dependency that way for a reason but, seeing as I've forgotten, hopefully it was just a simple mistake on my part.
