### ISSUE TITLE
Mending does not repair Elytra when in the back slot

### ISSUE THREAD

**Issue by Panduino** [TheIllusiveC4/CuriousElytra#13]
#### Versions (Be specific, do not write "latest"):
* Curious Elytra: 1.1.0
* Caelus: 0.0.15
* Curios: 0.0.11
* Forge/Fabric: 0.11.1
#### Steps to Reproduce:
1. Put mending on an elytra
2. Wear and damage it
3. Gain XP
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
Unfortunately, I cannot reproduce your issue. Using only Curious Elytra, Caelus, and Curios, the Mending enchantment works as expected in the back slot. Do you only have those mods installed? If not, can you replicate this with only those mods installed?

**Comment by Panduino** [comment]
> Unfortunately, I cannot reproduce your issue. Using only Curious Elytra, Caelus, and Curios, the Mending enchantment works as expected in the back slot. Do you only have those mods installed? If not, can you replicate this with only those mods installed?

Upon further investigation, it seems to work fairly inconsistently. Sometimes the elytra will get repaired and other times I'll have long stretches where it ends up breaking (without other mending gear) despite me gaining xp and seeing my levels go up

**Comment by TheIllusiveC4** [comment]
Does this issue occur with only Curious Elytra, Caelus, and Curios installed?

**Comment by Panduino** [comment]
Yes it does

**Comment by AlienXtream** [comment]
there was a similar issue with the "wireless crafting table curio" mod (the mod was removed as that feature was implemented in refined storage). it seems like curio slots arent ticked/updated the same way normal inventory slots are. as a result some things (like enchantment effects) are not accounted for. this is in fact the case with several other enchantments from other mods that add "repair" enchantments (solar, ecological, "indestructibility" which is basically a constant repair apparently). may even affect unbreaking but iv'e not tested that much. 

point is curio slots are not the same as inventory slots in how they are ticked so some added code may be required to make things work as intended, though what is needed i dont know. clearly its not as simple as adding a simple tag to the items though :/

**Comment by BenCrafterRED** [comment]
I can confirm the bug for the mod using Fabric/Trinkets. Gaining XP while having the Mending-enchanted Elytra in the Back slot, does not repair it. Tested using:
- Minecraft 1.19.1
- Elytra Slot 6.0.0
- Fabric Loader 0.14.8
- Fabric API 0.85.5
- Trinkets 3.4.0

**Comment by TheIllusiveC4** [comment]
@BenCrafterRED I cannot reproduce this. Using your versions as listed with only Trinkets, Fabric API, and Elytra Slot, the Mending-enchanted Elytra in the Back slot does indeed repair upon collecting experience.

When you are confirming the bug, did you _only_ have those mods installed? If not, you may need to locate the source of the mod incompatibility. If so, please provide your reproduction steps exactly.

**Comment by BenCrafterRED** [comment]
Indeed, I had Clumps (version 1.19.1-9.0.0+10) installed and after removing it, Mending worked like a charm.
