### ISSUE TITLE
[Bug]: 1.21 curios is dicontinued

### ISSUE THREAD

**Issue by thosegamer** [TheIllusiveC4/CuriousElytra#131]
### Minecraft Version

1.21.0

### What happened?

you need to remove curios as required dependency as it is discontiunued as of 1.21

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

Forge

### Mod Version

1.21

**Comment by TheIllusiveC4** [comment]
There are three ways to get Curios on 1.21: [Curios API Continuation](https://www.curseforge.com/minecraft/mc-mods/curios-continuation), [Adorned](https://www.curseforge.com/minecraft/mc-mods/adorned), and [Accessories](https://www.curseforge.com/minecraft/mc-mods/accessories) with their Curios compatibility layer. The first one is listed as the required dependency on the project page for 1.21.
