### ISSUE TITLE
[Bug]: Deeper Dark Soul Elytra boost no longer works in elytra slot

### ISSUE THREAD

**Issue by NolanHewitt** [TheIllusiveC4/CuriousElytra#132]
### Minecraft Version

1.20.1

### What happened?

Deeper Darker updated and this elytra's boost ability no longer works if its in the elytra slot

### Loader

Quilt

### Loader Version

0.26.3

### API Version

Newest

### Mod Version

6.4.2

**Comment by Fyoncle** [comment]
Can verify, Deeper And Darker broken at CTRL and SHIFT boost keys and others that is not the normal letters, and when it placed to the Elytra Slot, it ignores the keybinding and sets into SHIFT which is broken in the normal mod too.

**Comment by twenty41** [comment]
[also experiencing](https://github.com/KyaniteMods/DeeperAndDarker/issues/371)

**Comment by Broclly** [comment]
yea same thing happened when i was using it too :(

**Comment by Fyoncle** [comment]
@TheIllusiveC4 :(

**Comment by SanQianQVQ** [comment]
same problem

**Comment by randymac** [comment]
Same here with Accessories with Trinkets compat.  also get constant breaking sounds.
**https://github.com/illusivesoulworks/elytraslot/issues/134**

minecraft 1.21
fabric loader .16.5
[Accessories](https://modrinth.com/mod/jtmvUHXj) 1.0.0 beta .35
[Accessories Trinkets Compat Layer](https://modrinth.com/mod/TkWgV1AW) 3.10.0 Layer Beta.11 for 1.21

**Comment by Pohnx** [comment]
same thing happening to me as well. My game also crashes when I go to equip it on my eltytra trinket slot

**Comment by Fyoncle** [comment]
The issue still remains on my side. @TheIllusiveC4

**Comment by TheIllusiveC4** [comment]
Can you list your version number, mod loader, and MC version?

**Comment by Fyoncle** [comment]
> Can you list your version number, mod loader, and MC version?

1.20.1, Fabric, 6.4.4

**Comment by Fyoncle** [comment]
Boost no longer works if key is set to anything like Shift, Alt, Or any other thing by the way, normal keys like A B C D E works.

**Comment by Fyoncle** [comment]
For further information, i use Elysium Days 6.0.0 modpack

**Comment by TheIllusiveC4** [comment]
> Boost no longer works if key is set to anything like Shift, Alt, Or any other thing by the way, normal keys like A B C D E works.

Do these work when the elytra is equipped in the armor slot instead?

**Comment by Fyoncle** [comment]
> > Boost no longer works if key is set to anything like Shift, Alt, Or any other thing by the way, normal keys like A B C D E works.
> 
> Do these work when the elytra is equipped in the armor slot instead?

Still no i think. It seems like a Deeper & Darker bug.

**Comment by TheIllusiveC4** [comment]
> Still no i think. It seems like a Deeper & Darker bug.

Then this probably needs more investigation by them, as I don't do anything with the logic for their elytra in the armor slot. Also, for what it's worth, I can use SHIFT for boosting just fine in my testing environment so it may also potentially be a mod conflict on your end with something else.

**Comment by Fyoncle** [comment]
> > Still no i think. It seems like a Deeper & Darker bug.
> 
> Then this probably needs more investigation by them, as I don't do anything with the logic for their elytra in the armor slot. Also, for what it's worth, I can use SHIFT for boosting just fine in my testing environment so it may also potentially be a mod conflict on your end with something else.

Can u send a log from the testing environment for me to see the mod list and further information?
