### ISSUE TITLE
[Bug]: Elytra not working on trinket cape slot

### ISSUE THREAD

**Issue by mxarment** [TheIllusiveC4/CuriousElytra#138]
### Minecraft Version

1.21.0

### What happened?

Just that, I cant even start flying

### How do you trigger this bug?

1. Put the elytra on the cape trinket slot
2. Try flying

### Loader

Fabric

### Loader Version

Fabric Loader 0.16.5

### API Version

Fabric 0.105.0+1.21.1

### Mod Version

elytraslot-fabric-9.0.1+1.21.1

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, flying works as expected on my end. Have you tried testing with only Elytra Slot, Fabric API, and Trinkets installed? If not, it may be a mod conflict.

**Comment by mxarment** [comment]
yeah, you are right, i didnt realiced it could be that, sorry for bother you.

at the end it was ViaFabricPlus mod, idk what this mod does to do with trinket elytra, i supposed any change to be able to connect to the servers
