### ISSUE TITLE
Elytra renders with default textures when using resource pack with Optifine naming integration

### ISSUE THREAD

**Issue by dmdizzy** [TheIllusiveC4/CuriousElytra#14]
#### Versions (Be specific, do not write "latest"):
* Curious Elytra: curiouselytra-forge-1.16.5-4.0.2.0.jar
* Caelus: caelus-forge-1.16.5-2.1.2.2.jar
* Curios: curios-forge-1.16.5-4.0.4.0.jar
* Forge/Fabric: forge-35.1.36
#### Steps to Reproduce:
1. Install Optifine and a texture pack that supports Optifine's naming features with Elytra
2. Rename an Elytra in an anvil with one of the resource pack's supported names
3. Place Elytra in the Curios back slot

**Comment by TheIllusiveC4** [comment]
I don't think there's much I can do here. I don't believe Optifine has an API available for hooking into their texture changes and my hands are tied on my end because Optifine itself is closed-source.
