### ISSUE TITLE
Elytra doesn't show enchant glint when enchated

### ISSUE THREAD

**Issue by The-VoidX3** [TheIllusiveC4/CuriousElytra#15]
#### Versions (Be specific, do not write "latest"):
* Curious Elytra: 1.1.1
* Caelus: N/A
* Curios: 0.0.11
* Forge/Fabric: Fabric 0.1.11
#### Steps to Reproduce:
1. enchant elytra
2. put elytra in back slot
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
Please fill out the bug report template properly with version numbers and reproduction steps.
