### ISSUE TITLE
Client crashes when equipping elytra in back slot

### ISSUE THREAD

**Issue by KingNin64** [TheIllusiveC4/CuriousElytra#18]
Versions:
* Curious Elytra: Forge 1.16.5, version 4.0.3.5
* Caelus: Forge 1.16.5, version 2.1.3.0
* Curios: Forge 1.16.5, version 4.0.5.0
* Forge/Fabric: Forge
Observed Behavior: I stopped my server to add Curious Elytra after discovering that my newly crafted Silent Gear elytra could be equipped to a back slot. Upon starting my server again, I could not connect. My brother, who didn't have his elytra already equipped, was able to join. However, when he equipped his elytra, it crashed his client.
Expected Behavior: Happily flying away with my elytra.
Steps to Reproduce:
1. Use Silent Gear.
2. Craft an elytra using the SGear blueprint (I used only phantom membrane; idk if that is important).
3. Use the above versions of Curious Elytra, Curios, and Caelus, as well as Silent Gear 2.6.0+217.
4. Equip elytra in back slot.
5. (not sure if these steps will reproduce the problem exactly, but these are the only steps I did other than already having other mods installed, which you can see in the crash log).
...

Crash Log: https://pastebin.com/4SRyjuKQ

**Comment by TheIllusiveC4** [comment]
You listed your Caelus version as 2.1.3.0, however the one you actually have loaded in the crash log is 2.1.2.2.

Update Caelus to 2.1.3.0 and that should fix your issue.
