### ISSUE TITLE
Incompatibility with unknown mod causing failures upon reconnect

### ISSUE THREAD

**Issue by endigma** [TheIllusiveC4/CuriousElytra#19]
#### Versions (Be specific, do not write "latest"):
* Curious Elytra: curiouselytra-forge-1.16.5-4.0.2.3
* Caelus: caelus-forge-1.16.5-2.1.3.0
* Curios: curios-forge-1.16.5-4.0.5.0
* Forge/Fabric: 36.0.58
#### Observed Behavior:
When disconnect/reconnect from SP or MP, elytra inside the curios back slot are moved to inventory, but render on the character in third person until inventory is opened.

#### Expected Behavior:
Elytra should persist and remain functional in the Curios back slot.

#### Steps to Reproduce:
1. Download my very particular set of mods
2. Load into a world
3. Equip Elytra in curios back slot
4. Disconnect
5. Reconnect

I've established through trial and error that this is an incompatibility with another mod in my list, as running only Caelus, CuriosElytra and Curios it works as expected. I'm creating an issue because quite frankly I have no idea where to look for an incompatibility, and in a modlist of 120 it's not feasible to manually add each one until the error represents itself. I'd be happy to provide any information required for testing/reproducing. Modlist is in the log, however I'll also provide it for ease of access.

Crash Log: [logfile](https://haste.cya.cx/uqewexaras.log).

Modlist: [modlist](https://haste.cya.cx/doqoqoreli)

**Comment by endigma** [comment]
Also of note might be a peculiarity where when equipping the elytra in survival using right click, it initially looks like it was added to the chest-plate slot, however if you click the curios inventory button it transfers to the `back` slot. In creative this results in a dupe, and in survival if you try to move the chest-plate elytra it also updates to be in the curios slot.

**Comment by TheIllusiveC4** [comment]
So there are a couple mods that add their own elytras, which might be the source of the issue. Have you tried reproducing this with Enderite Mod and Netherite Plus?

**Comment by endigma** [comment]
If this is the case, is the only fix to remove these mods? I'll test this in a few hours.

**Comment by TheIllusiveC4** [comment]
I'm not saying they're definitely the cause, I'm saying it's possible since they add their own elytras so testing those in particular may be worthwhile.

**Comment by endigma** [comment]
> I'm not saying they're definitely the cause, I'm saying it's possible since they add their own elytras so testing those in particular may be worthwhile.

I'll test and post when I have a result. Next hour or so I'm sorting out another issue.

**Comment by endigma** [comment]
The bug is not reproducible with:
- architectury-1.8.131-forge
- enderitemod-1.16.3-0.7.0-forge-34.1.34
- netherite-plus-mod-1.4.0-1.16.5-forge

in addition to the curios/caelus/ce noted in the OP.

**Comment by TheIllusiveC4** [comment]
Hm, that's interesting. I'll have to investigate this deeper then.

**Comment by endigma** [comment]
If it comes to it, I might end up doing a batch 50/50 sort to figure out what mod it is. Would theoretically only take 7 tests to figure out what mod it is, give or take a few because you can't really split the modlist in half because of dependencies etc.

**Comment by endigma** [comment]
@TheIllusiveC4 

I went through about an hour of testing, and I've reproduced the bug with:

https://haste.cya.cx/vuqotubiga

Notably, the issue does not occur with only abnormals core installed, confirming this is an issue with endergetic.
