### ISSUE TITLE
Elytra being removed while exiting The End

### ISSUE THREAD

**Issue by AlbyNexus** [TheIllusiveC4/CuriousElytra#2]
#### Notice:
If you exit the End using the dragon's portal with Elytra equipped in curious inventory, Elytra is no longer present when you came back to the Overworld.

#### Versions:
* Curious Elytra: FORGE-1.14.4-0.7
* Caelus: FORGE-1.14.4-0.10
* Curios: FORGE-1.14.4-0.20
* Forge: 28.0.41

#### Steps to Reproduce:
1. Equip your Elytra in the curious inventory slot
2. Exit the End using the main portal
3. Elytra is no longer present when you came back in the Overworld

**Comment by TheIllusiveC4** [comment]
Update Curios, this should be fixed as of version 0.22 (latest is 0.24).
