### ISSUE TITLE
Netherite Elytra render glitch

### ISSUE THREAD

**Issue by Tortyash** [TheIllusiveC4/CuriousElytra#21]
Netherite Elytra invisible when used in Curios slot
![2021-03-23_14 32 38](https://user-images.githubusercontent.com/45497877/112147021-e6728000-8be4-11eb-90a6-d85b0f9f637a.png)
![2021-03-23_14 32 49](https://user-images.githubusercontent.com/45497877/112147028-e7a3ad00-8be4-11eb-8796-b066f9c7a4ad.png)
Mods used:
1.16.5-forge-36.1.0
architectury-1.10.138-forge
caelus-forge-1.16.5-2.1.3.0
curios-forge-1.16.5-4.0.4.0
curiouselytra-forge-1.16.5-4.0.2.3
netherite-plus-mod-1.4.1-1.16.5-forge

**Comment by TheIllusiveC4** [comment]
This is fixed in 1.16.5-4.0.2.4.
