### ISSUE TITLE
Allow turning off Elytra activation via keybind

### ISSUE THREAD

**Issue by TheRealWormbo** [TheIllusiveC4/CuriousElytra#22]
The proposed change is a new configurable key binding called something like "Toggle Elytra" or "Toggle Elytra Activation" that toggles whether using the jump key in mid-air activates the elytra. (It should probably start unbound to prevent accidents.)

Augmenting the elytra flight with either a multi-jump feature or a jetpack can greatly improve mobility without using rockets. However, the same features sometimes provide better vertical mobility without the elytra, so you need to manually open the curio inventory and unequip the elytra in order to use e.g. a hover feature or precisely multi-jump onto some pillar. Here a keybind to disable the elytra activation would save a lot of additional effort. A similar feature was present in the 1.12 Colytra mod and I found it very useful for switching between jetpack-assisted local movement and elytra-assisted travel.

**Comment by ScoobyVI** [comment]
Hi, I came across this page while looking for mods that add this functionality.

Another use case for this is compatibility with mods that add things like double-jump enchantments. Anything that relies on using 'Space' while airborn conflicts with Elytra flight. Even just moving around and jumping a lot is annoying with an Elytra equipped - It would be really nice to have a 'Toggle Elytra Flight' keybind if that's a possibility. Bedrockify just released an update that allows you to cancel flight while airborn, but not with a custom keybind

**Comment by TheIllusiveC4** [comment]
This is a feature that used to be in Colytra, then used to be in Caelus, and now I've properly spun it into its own mod where it will live for the foreseeable future:

https://www.curseforge.com/minecraft/mc-mods/elytra-utilities
