### ISSUE TITLE
game freezes when ever i try to load a new world or make a new world

### ISSUE THREAD

**Issue by potatopepe** [TheIllusiveC4/CuriousElytra#23]
#### Versions (Be specific, do not write "latest"):
* Curious Elytra: 1.1.1-1.16.5
* Caelus: 0.0.15-1.16.4
* Curios: 0.0.13-1.16.4
* Fabric API : 0.34.2-1.16.5
* Forge/Fabric: fabric-loader-0.11.3-1.16.5
#### Steps to Reproduce:
1. down load all mods stated above
2. make or load a world
3. game freezes 
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/):
i can't provide a crash log since the game doesn't even crash and you are forced to stop via the task manager

**Comment by zeresss** [comment]
same, but sometimes it crashes, so here is crash log
https://hastebin.com/share/ijanuticey.yaml

**Comment by TheIllusiveC4** [comment]
> same, but sometimes it crashes, so here is crash log
https://hastebin.com/share/ijanuticey.yaml

This is an old issue with probably a different cause. If you're experiencing an issue, please open up a new issue report rather than post in this one.
