### ISSUE TITLE
It isn't working with the spectral Elytra wen I try to put it in the slot

### ISSUE THREAD

**Issue by Chronic1es** [TheIllusiveC4/CuriousElytra#24]
#### Versions (Be specific, do not write "latest"):
* Curious Elytra:
* Caelus:
* Curios:
* Forge/Fabric:
#### Observed Behavior:
It isn't going into the slot
#### Expected Behavior:
It working being able to put it in the slot
#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
Please fill out the version numbers in the bug report template.

**Comment by TheIllusiveC4** [comment]
This is fixed in 1.16.5-4.0.2.4.
