### ISSUE TITLE
Netherite Elytra added to the back Curios.

### ISSUE THREAD

**Issue by GameKnight6067** [TheIllusiveC4/CuriousElytra#25]
The Netherite elytra mod is a great mod to help with durability and make sure it can't burn in lava, I was wondering if that could be added to the curios elytra mod.

**Comment by ghost** [comment]
The Netherite Elytra can now be added to the Back slot via a mod update, but it does not consume durability.  Could you use `instanceof` instead of `stack.getItem() == Items.Elytra`  in VanillaElytraProvider, maybe for better compatibility?

Thanks
