### ISSUE TITLE
Incompatible with FallFlyingLib (Bundled with Origins)

### ISSUE THREAD

**Issue by Oliver-makes-code** [TheIllusiveC4/CuriousElytra#27]
#### Versions (Be specific, do not write "latest"):
* Elytra Trinket: 2.0.1
* Caelus: 0.0.16+1.17
* Trinkets: 3.0.0
* Forge/Fabric: Fabric 1.17
#### Observed Behavior:
Elytra will not work
#### Expected Behavior:
Elytra should work, but FallFlyingLib prevents it
#### Steps to Reproduce:
1. Install FallFlyingLib (Bundled with origins)
2. Install this mod and its dependancies
3. Try flying with an elytra in the trinket slot

**Comment by TheIllusiveC4** [comment]
This is fixed on Caelus's end. Please download 0.0.17-1.17 of Caelus to override the outdated version bundled with Elytra Trinket.
