### ISSUE TITLE
AlexMobs tarantula_hawk_elytra support

### ISSUE THREAD

**Issue by Sam-Chai** [TheIllusiveC4/CuriousElytra#28]
**Please describe the new feature or change.**
alexmobs' tarantula_hawk_elytra support

**Please describe why you want this feature.**

![image](https://user-images.githubusercontent.com/29940426/125613015-9c9e256d-76c6-43ff-977c-ef2ab7115c08.png)
![image](https://user-images.githubusercontent.com/29940426/125613058-c3d9402b-bab3-4c0e-ba12-c9273876921a.png)

**Comment by SargRReal** [comment]
I too would like this feature, otherwise the tarantula hawk elytra is next to useless with this mod

**Comment by antoine-courant** [comment]
Hello
I'll just add my wish upon the add of this feature, Alexmob is a pretty popular mod around here (tho it's sad those Elytras aren't working at the moment, I wonder if it works for you guys)
