### ISSUE TITLE
[1.15.2] Weird cape behaviour

### ISSUE THREAD

**Issue by Omni35** [TheIllusiveC4/CuriousElytra#3]
#### Versions:
* Curious Elytra: curiouselytra-FORGE-1.15.2-2.0
* Caelus: caelus-FORGE-1.15.2-2.0-beta2
* Curios: curios-FORGE-1.15.2-2.0.2.2
* Forge: 31.2.0

#### Observed Behavior 
No cape present until an elytra is put on the curios slot.

#### Expected Behavior 
Cape should be visible without an elytra. Putting an elytra on should hide the cape.

#### Steps to Reproduce 
1. No elytra equipped = cape is never visible.
2. Put on an elytra in the curios slot = cape is show along with it's pattern on the elytra.

#### Other mods (necessary to reproduce the bug)
* OptiForge-MC1.15.2-0.1.19
* OptiFine_1.15.2_HD_U_G1_pre18
* MixinBootstrap-1.0.3

#### Additional Info
Putting an elytra on the vanilla chestplate slot doesn't show the cape but does show the cape pattern on the elytra, same behaviour present with only Caelus-Forge installed, no cape is shown at all even when equipping an elytra, altho the cape pattern gets applied to it.

![ThOps4tYu5](https://user-images.githubusercontent.com/7506611/83063000-c6733e00-a05f-11ea-9dc2-37b0fc3c91a6.gif)

**Comment by TheIllusiveC4** [comment]
I'm not really familiar with capes so I need to ask first, are you using an official cape or obtaining it through some other method?

**Comment by Omni35** [comment]
It's an OptiFine supporter cape, anyone using OF can see it, mine uses a banner pattern. 
Afaik they work just like official ones, don't think I got access to an official one to check tho.

**Comment by TheIllusiveC4** [comment]
Hmm, just so that I've got this right:

With only Caelus, Forge, Optifine, Optiforge, and MixinBootstrap:
1. Capes never appear even with an elytra in the curios slot
2. Elytras gain the correct cape pattern

With all of the above + Curious Elytra:
1. Capes do not appear unless you equip elytra into the curious slot
2. Elytras gain the correct cape pattern

Is that correct?

**Comment by Omni35** [comment]
Yes, that's correct.

**Comment by TheIllusiveC4** [comment]
Documented on https://github.com/TheIllusiveC4/Caelus/issues/5
Please follow there for further updates
