### ISSUE TITLE
Modded Enchantments not working while Elytra is equipped in the Back Slot.

### ISSUE THREAD

**Issue by hstheperson** [TheIllusiveC4/CuriousElytra#30]
#### Versions:
* Curious Elytra: curiouselytra-forge-1.16.5-4.0.2.3.jar
* Caelus: caelus-forge-1.16.5-2.1.3.1.jar
* Curios: curios-forge-1.16.5-4.0.5.3.jar
* Forge: 36.2.6
#### Steps to Reproduce:
1. Have an Elytra enchanted with modded enchantments.
    A. I have noticed it when attempting to use _Winging_ from the _More Enchantments_ mod. Winging is meant to deploy the Elytra automatically when falling. _Reparation_ (from the same mod) also does not function as intended.
    B. Link to aforementioned mod: https://www.curseforge.com/minecraft/mc-mods/more-enchantments
2. Attempt to have enchantments work.
3. See that enchantments, in fact, do not work

Crash Log: No crashes, only failure to activate enchants.

**Comment by TheIllusiveC4** [comment]
This is much more easily done on the side of the mod implementing the enchantments. For example, _More Enchantments_ can add integration to check for the curios slot in addition to the armor slot when applying their behavior. Whereas to get that same integration on my end, I would need to replicate their entire enchantment logic. And I would have to do this for every mod that adds an elytra enchantment. It's just much more work, and may not even be feasible depending on how the particular enchantments are coded.

So I'd suggest making this integration request to the enchantment developers.

Edit: I should mention that labeling this as a "bug" is a bit of a misnomer, as it's expected that enchantments do not work automatically with curios. This is more aptly a feature request for the implementing mod to include optional curios slot checks in their enchantment logic.
