### ISSUE TITLE
If put vanilla Elytra on the back slot, I can't fly

### ISSUE THREAD

**Issue by ksk-waqs** [TheIllusiveC4/CuriousElytra#33]
If put vanilla Elytra on the back slot, I can't fly
----
* Curious Elytra: curiouselytra-forge-1.16.5-4.0.2.3.jar
* Caelus: caelus-forge-1.16.5-2.1.3.1.jar
* Curios: curios-forge-1.16.5-4.0.5.3.jar
* Forge/Fabric: forge 36.2.2

**Comment by TheIllusiveC4** [comment]
I can't reproduce this, using your version numbers the back slot vanilla Elytra works fine for me. Did you test this with _only_ those mods installed?

**Comment by ksk-waqs** [comment]
![image](https://user-images.githubusercontent.com/3883054/141442258-2250e827-41af-4a7a-8e15-f4a40c8fa138.png)
Yes, I put only the necessary mods for the test and still the Elytra do not work

**Comment by ksk-waqs** [comment]
Anyway, here's what I found out. The Elytra work in your slot in all cases except when I try to launch fireworks without bouncing (although it works with regular ones).

Since I found out during my tests that this option is most likely given by some mod and your mod works correctly, I'm closing the thread.
