### ISSUE TITLE
Add (optional) support for Mana & Artifice "spectral elytra"

### ISSUE THREAD

**Issue by nivthefox** [TheIllusiveC4/CuriousElytra#34]
**Please describe the new feature or change.** Mana & Artifice adds an item called a "spectral elytra" which functions like a regular elytra, except that it is powered by mana instead of rockets. I would like Curious Elytra to support moving this elytra to a curio slot.   Its item ID is `mana-and-artifice:spectral_elytra`

**Please describe why you want this feature.**  The mod author has suggested he's not interested in his elytra being a curio because the default isn't, and he thinks that balance is important.    I think that's a reasonable take, and since your mod is designed for people who DON'T like that balance aspect, it would make sense to me if Curious Elytra was the solution for a curio for all mod-added elytras.

**Comment by TheIllusiveC4** [comment]
This compatibility already exists in the latest version. Which version of Curious Elytra are you using?

**Comment by Rynex21** [comment]
I have some issue relating to this, let me explain:

I was using Mana and Artifice version [1.16.5-1.5.1.7] and Curious Elytra (Forge) version [1.16.5-4.0.2.4].

Spectral Elytra supposedly use mana constantly to propel you at the direction you are looking at while flying.

However, when equiped on back slot you will instead glide in the air like normal elytra.

**Comment by nivthefox** [comment]
@TheIllusiveC4 Update several months later: you can definitely put the armor in the curio slot if you add a datapack which adds the appropriate tags to the item (which I think curious elytra should probably do for you), but the Spectral Elytra does not FUNCTION in that slot, even as a basic elytra.  It doesn't even show the layer on the model, so it looks like the spectral elytra is not equipped.

**Comment by nivthefox** [comment]
@TheIllusiveC4 Update: It looks like the problem is because Mithion changed from `mana-and-artifice` to `mna` when he changed to 1.18.  I can provide a pull request to patch this (or support both) if you would like?

**Comment by TheIllusiveC4** [comment]
That's alright, thank you. Since you've identified the source of the issue, I should be able to address it in the next update.

**Comment by nivthefox** [comment]
Sounds great!   Will you be re-releasing for 1.18.2 for that, or just waiting for M&A to eventually reach 1.20?

**Comment by TheIllusiveC4** [comment]
Updating for 1.18.2.
