### ISSUE TITLE
Elytras and capes

### ISSUE THREAD

**Issue by DelofJ** [TheIllusiveC4/CuriousElytra#36]
#### Versions:
* Minecraft: 1.17.1
* Elytra Trinket: 2.0.1
* Caelus: 0.0.18
* Trinkets: 3.0.4
* Forge/Fabric: Fabric
* Fabric API: 0.44.0
* Fabric Loader: 0.12.11

#### Observed Behavior:
There is a cape at the same time as the elytra

#### Expected Behavior:
There wouldn't be a cape at the same time as the elytra

#### Steps to Reproduce:
1. Have a Minecraft cape
2. Install the mods
3. Put the Elytra in the Cape slot
4. When you move, you'll see the cape at the same time as the elytra, which does not happen in the normal slot

Crash Log: There is no crash, but here is the latest.log on [hastebin](https://www.toptal.com/developers/hastebin/amidedivaj.yaml).

Screenshot:
![Elytra Trinket and cape](https://user-images.githubusercontent.com/50058956/145729400-56662448-1a73-42de-89db-a1b79de265b6.png)
 
Note:
The custom cape is in vanilla

**Comment by TheIllusiveC4** [comment]
This should be fixed in 3.0.0-1.17.1.
