### ISSUE TITLE
[1.18.1] New version keeps crashing the game and messing other mods.

### ISSUE THREAD

**Issue by ffuentesm** [TheIllusiveC4/CuriousElytra#37]
#### Versions (Be specific, do not write "latest"):
* Curious Elytra: curiouselytra-forge-1.18.1-5.0.0.0.jar
* Caelus:  caelus-forge-1.18-3.0.0.1.jar
* Curios: curios-forge-1.18.1-5.0.3.0.jar
* Forge: 39.0.5
#### Steps to Reproduce:
1. install bott JEI and Toolbelt, then install the latest curious elytra
2. Either you can't load the world, the JEI overlay will not show up, or you can't add the tool belt to the belt slot.
3. IF you uninstall Curious Elytra, those problems go away.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://crashy.net/80r3z14qxwmHSk2te8CR

**Comment by Tokerot** [comment]
Similar issues here, same versions as op, similar but not identical mod-list. Game crashes with Curious Elytra but works without it. I can load into a new world fine but trigger the crash by changing resource packs but anything that reloads the world will trigger the crash, I've tried turning on off other mods that use curio but couldn't determine a specific mod conflict, haven't done further testing. https://crashy.net/kTpRwa8fxUnhKreRqMLv

**Comment by TheIllusiveC4** [comment]
I'm having some trouble reproducing this. Are either of you able to reproduce this with _only_ Curious Elytra (and its dependencies) installed? Even with JEI and Tool Belt, nothing happens for me.

**Comment by ffuentesm** [comment]
Yes, is strange. When I create a new profile with just Curious Elytra (and its dependencies) + JEI and Toolbelt. There is nothing wrong. 
But when I use in my usual mod pack. Curious Elytra is the one to break things.

**Comment by Tokerot** [comment]
turns out its curios of undying that is clashing, here is it crashing using only curio elytra and curio undying, if i remove one or the other there is no crash, but together results in crash https://crashy.net/O1JNsMufEWLN6pfRmjYC

**Comment by ffuentesm** [comment]
Not for me, I tried the version without curios of undying and turned on Curious Elytra.
and I get the same error when I try to load a single player world, this happens
![image](https://user-images.githubusercontent.com/44974827/146485538-c6b702c3-7350-46f3-be61-a2ab9491f72f.png)
It acts as if I tried to enter in a server. 

And when I manage to load the world, I get this crash
https://crashy.net/5eL0UcYWfZa0G0391fcE
https://bytebin.lucko.me/80o7eZJgPZ
![image](https://user-images.githubusercontent.com/44974827/146485690-55799a5f-de32-46ce-9742-c9da339280a9.png)

**Comment by TheIllusiveC4** [comment]
Ah ok, I get what's going on here. Fix incoming.
