### ISSUE TITLE
Optifine CIT Resourcepack Fails to load

### ISSUE THREAD

**Issue by PhantomLeopard** [TheIllusiveC4/CuriousElytra#38]
I have my own Resourcepack that I use for my own textures, which utilities both item and model textures, through Optifine CIT. However, I think that the elytra trinket slot will not be able to have Optifine cit textures. I was using the. Now, this resourcepack worked perfectly under normal conditions, but when in the elytra trinket slot, it converted back the vanilla model, as I think that Optifine CITs fail to render or something. If you could fix this bug, (if it isn't a bug, could you please add it in a feature), that would be the best! Thanks! (I submitted this as an issue to the trinkets mod, and they said it was the problem with this mod instead)

Versions
Trinkets: trinkets-3.1.0
Elytra Trinket: elytratrinket-fabric-3.0.0-1.18.1
Here are some images to show the problem.
![2021-12-24_13 03 06](https://user-images.githubusercontent.com/81445352/147820759-d217458b-f55b-4573-af8b-52a712a8ce69.png)
![2021-12-24_13 02 49](https://user-images.githubusercontent.com/81445352/147820770-e312a79a-a497-4c08-a212-f245e997265e.png)
![2021-12-24_13 02 53](https://user-images.githubusercontent.com/81445352/147820779-b80d99bc-426b-452a-9675-94d630f6f746.png)
![2021-12-24_13 03 02](https://user-images.githubusercontent.com/81445352/147820791-b49e4b4a-6eaa-44d8-b005-6f92288c14f3.png)

**Comment by TheIllusiveC4** [comment]
Unfortunately, since Optifine is closed source there's not much I can do in terms of compatibility. As far as I'm aware, I don't have any way to interact with their CIT logic.

**Comment by PhantomLeopard** [comment]
> Unfortunately, since Optifine is closed source there's not much I can do in terms of compatibility. As far as I'm aware, I don't have any way to interact with their CIT logic.

Would this be a problem with Optifine themselves or Optifabric?
