### ISSUE TITLE
won't start on server

### ISSUE THREAD

**Issue by chrissurfer** [TheIllusiveC4/CuriousElytra#4]
i added it to my server but doesn't work at all 
[latest.log](https://github.com/TheIllusiveC4/CuriousElytra/files/4881796/latest.log)

**Comment by TheIllusiveC4** [comment]
This is a Forge mod, but it seems you're using a Bukkit server.

**Comment by chrissurfer** [comment]
is there a server version 
i know I need two mods

**Comment by chrissurfer** [comment]
oh so no bucket/paper version?

**Comment by TheIllusiveC4** [comment]
Nope

**Comment by chrissurfer** [comment]
could you make one or could i/ configure it
