### ISSUE TITLE
Update dependency from Curios to Trinkets

### ISSUE THREAD

**Issue by silentnyte** [TheIllusiveC4/CuriousElytra#41]
When adding Curious Elytra to a profile using CurseForge desktop Curios API is required even if Trinkets API is installed.

**Comment by TheIllusiveC4** [comment]
If you're on 1.16.5, Curious Elytra uses Curios API. It changed its name to Elytra Trinket on Fabric and converted to using the Trinkets API in 1.17+. If you're on 1.17+ and it still downloads Curios API, then this is a CurseForge issue because all the files are correctly marked already.
