### ISSUE TITLE
support better end's armed elytra and crystal elytra

### ISSUE THREAD

**Issue by Q2297045667** [TheIllusiveC4/CuriousElytra#42]
**Please describe the new feature or change.**
![图片](https://user-images.githubusercontent.com/42416195/151291259-e908553f-16a1-4a72-b326-e45c059e1922.png)
![图片](https://user-images.githubusercontent.com/42416195/151291269-745dd771-2f0a-4451-844a-a5df4a95d06d.png)
![图片](https://user-images.githubusercontent.com/42416195/151291281-8e37cf19-3d58-4626-bbde-4be106826a51.png)

**Please describe why you want this feature.**
I modified mod, but it doesn't work on elytra trinket
BetterEnd link:https://www.curseforge.com/minecraft/mc-mods/betterend

**Comment by DisNetDev** [comment]
Would love to see this aswell

**Comment by TheIllusiveC4** [comment]
It looks like BetterEnd added Trinkets support on their end so I'll be closing this.
