### ISSUE TITLE
Use slot for other modded Elytra/Wing

### ISSUE THREAD

**Issue by ardissaps** [TheIllusiveC4/CuriousElytra#45]
**Please describe the new feature or change.**
Is it possible to make modded Elytra/Wing be able to use the slot provided? thx in advance

**Please describe why you want this feature.**
Be able to use modded Elytra/Wing on the provided slot.

**Comment by def-SpaceWar** [comment]
Yes, this is a really important feature, in the betterend mod there are 2 new elytras that can't be used in the elytra trinket slot.

**Comment by ardissaps** [comment]
> Yes, this is a really important feature, in the betterend mod there are 2 new elytras that can't be used in the elytra trinket slot.

Maybe on BE/BN side, coz icarus wing can use the slot properly.
