### ISSUE TITLE
Add project to modrinth.com

### ISSUE THREAD

**Issue by Sammcb** [TheIllusiveC4/CuriousElytra#47]
Hi, would it be possible for you to add this mod to [modrinth](https://www.modrinth.com)?

Modrinth is an open source alternative to CurseForge and offers a great API for users to interact with mods and modpacks. I am building a script to help manage modpacks that uses the modrinth API. I really like this mod and would love to see it on Modrinth so I can add it to the modpack I am creating!

Thanks so much!

**Comment by identithree** [comment]
+1, Would be great because Modrinth modpacks can't pull from CF's CDN anymore because their lawyers suck.
Current solution is to build another one and put it up on Modrinth, which I might do Soon:tm:

**Comment by TheIllusiveC4** [comment]
I'm certainly interested in adding all of my mods to Modrinth, I just need to find a good opportunity in between working on the mods themselves. I'll try to make it a priority this month since it seems there is growing interest in seeing this done.

**Comment by Sammcb** [comment]
Hey @TheIllusiveC4! Just curious if you have an ETA on this. Thanks so much!

**Comment by TheIllusiveC4** [comment]
@Sammcb Sorry for the delay, I had planned to get this done much earlier than this. But I'm starting the upload process now for all of my mods to Modrinth, you should be seeing this one pop up within the next few days.

**Comment by Sammcb** [comment]
That's great to hear, thank you so much!

**Comment by TheIllusiveC4** [comment]
https://modrinth.com/mod/elytra-slot
