### ISSUE TITLE
Add support for the MinecraftCapes mod

### ISSUE THREAD

**Issue by ConnixTV** [TheIllusiveC4/CuriousElytra#48]
Currently, when I place my elytra in the back slot, it shows my default elytra (or in this case, my Migrator cape) and not the elytra skin I have with MinecraftCapes. It also still renders my cape from MinecraftCapes along with the Elytra.

I also occasionally use an OptiFine cape, but that one works as expected.

Here's a video to better show what is happening:

https://user-images.githubusercontent.com/97262402/181168543-6d136cda-d5b2-437a-92e0-66a048f3ef26.mp4

**Comment by TheIllusiveC4** [comment]
Although I've just added the feature to have the elytra use the cape texture, I should mention that the cape will still render when using the elytra. MinecraftCapes doesn't expose an API method to change their cape rendering for me to use.
