### ISSUE TITLE
Compatibility with Inventory

### ISSUE THREAD

**Issue by ghost** [TheIllusiveC4/CuriousElytra#49]
Make the mod compatible with the **Inventory** mod. 
Now if they are used together the elitra slot is **not displayed**

**Comment by TheIllusiveC4** [comment]
Can you link the Inventory mod? Searching on CurseForge leads to several possible candidates and I'm not sure which you're talking about.

**Comment by ghost** [comment]
Sure. This one:
https://www.curseforge.com/minecraft/mc-mods/elytra-slot-fabric

**Comment by TheIllusiveC4** [comment]
You linked this mod, I'm asking for the Inventory mod.

**Comment by ghost** [comment]
Sorry, wrong link.
This one: https://www.curseforge.com/minecraft/mc-mods/inventorio

**Comment by TheIllusiveC4** [comment]
This is an issue for either Trinkets or Inventorio to handle, Elytra Slot doesn't handle any part of the inventory itself.
