### ISSUE TITLE
[1.16.1] Requires Caelus API in version 3.0

### ISSUE THREAD

**Issue by dierks-m** [TheIllusiveC4/CuriousElytra#5]
Starting MC 1.16.1 with Forge version 32.0.63 and Curious Elytra v3.0 requires Caelus API v3.0-beta1, but the only one available on CurseForge (and GitHub) is 2.0-beta4.
The gradle.properties in the CaelusAPI repository also only says it's v2.0-beta4 [(TheIllusiveC4/Caelus#16afeb8)](https://github.com/TheIllusiveC4/Caelus/commit/16afeb8bf8c9eedf6523443ec6ec87cea9916094)

**Comment by TheIllusiveC4** [comment]
Are you mistaking Caelus for Curios? Curios is the dependency that requires v3.0-beta1.
