### ISSUE TITLE
compatibility with Tinkers Construct mod  (slime elytra)

### ISSUE THREAD

**Issue by EvilToasterDBU** [TheIllusiveC4/CuriousElytra#52]
Please add support slime elytra from Tinkers Construct mod (1.16.5+)

**Comment by Landrozaum** [comment]
i think he will not but i wait this also (last 1.18 update was in january)

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/illusivesoulworks/elytraslot/issues/43
