### ISSUE TITLE
Request to Santa

### ISSUE THREAD

**Issue by Psychodeus** [TheIllusiveC4/CuriousElytra#54]
![image](https://user-images.githubusercontent.com/93028949/196835389-d641e958-54e5-4a0f-8414-9762d69004ed.png)

Hey, could you please add Forge style to Fabric version? I like the Forge better.
## Another questions

1. Is the Elytra still attached when the player died? (I hope not)
2. Is it compatible with [Elytra Physics](https://www.curseforge.com/minecraft/mc-mods/elytra-physics)?
3. Is it compatible with any resorce pack?
4. Are you okay?

**Comment by TheIllusiveC4** [comment]
Unfortunately, there's no way to just change the style of the inventory. Curios and Trinkets, while they accomplish the same goals, are fundamentally different APIs and I cannot just apply one onto another.

As for your questions, and my apologies for the late response:
1. No.
2. Yes.
3. It should be.
4. Yes, thanks for asking.
