### ISSUE TITLE
Add Compatibility with Alex's Mobs

### ISSUE THREAD

**Issue by LolJohn11** [TheIllusiveC4/CuriousElytra#55]
Please add support for [Alex's Mobs](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs) since it has an elytra item called "Tarantula Hawk Elytra". 
I think two big mods like yours and Alex Mob's should be compatible as many people will appreciate it.

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/illusivesoulworks/elytraslot/issues/28
