### ISSUE TITLE
Elytra isn't receiving Mending benefits

### ISSUE THREAD

**Issue by purejosh** [TheIllusiveC4/CuriousElytra#56]
#### Versions (Be specific, do not write "latest"):
* Elytra Slot: elytraslot-fabric-6.0.0+1.19.2
* Caelus (Forge only):
* Curios/Trinket: trinkets-3.4.0
* Forge/Fabric: Fabric 1.19.2
#### Steps to Reproduce: 
1. Install Trinket, Elytra slot, and CosmeticArmor-1.19-1.4.0.
2. Put a mending elytra in the wing slot. 
3. Observe that the elytra does not mend with experience gained. 
...

Crash Log: Please use a paste site like [pastebin](https://pastebin.com/).

**Comment by jmadarg** [comment]
This bug is actually caused by the Trinkets mod, and its fixed in the latest update ( https://github.com/emilyploszaj/trinkets/pull/222 ); It also happens if you have Clumps installed, but for a different reason I think ( https://github.com/jaredlll08/Clumps/issues/109 )

**Comment by purejosh** [comment]
Interesting, thank you. I'll get those updated.

**Comment by TheIllusiveC4** [comment]
> It also happens if you have Clumps installed, but for a different reason I think ( https://github.com/jaredlll08/Clumps/issues/109 )

Yes, that's for a different reason and needs to be addressed on Clumps's end.
