### ISSUE TITLE
Mending does not function with elytra in trinket slot

### ISSUE THREAD

**Issue by SCPRedMage** [TheIllusiveC4/CuriousElytra#58]
#### Versions (Be specific, do not write "latest"):
* Elytra Slot: 6.0.0
* Trinket: 3.4.1
* Fabric: 0.14.10
#### Steps to Reproduce:
1. Enchant an elytra with mending
2. Put enchanted elytra in trinket slot
3. Collect XP

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, testing this on my end results in the elytra with Mending being repaired.

Please list out more detailed reproduction steps, also make sure to test this with ONLY these mods installed to avoid mod conflicts. For instance, Clumps is a known mod that causes Trinkets Mending to fail.

**Comment by NighthowlerStudios** [comment]
Had an issue just like this occur with unbreaking.  Possible mod collision is Lithium (we use the Roadrunner fork)

**Comment by TheIllusiveC4** [comment]
> Had an issue just like this occur with unbreaking. Possible mod collision is Lithium (we use the Roadrunner fork)

This seems like an unrelated issue to the original. If this is still a problem, please open up a new issue report for investigation.
