### ISSUE TITLE
Game crash when looting XP with damaged mending elytra in the back slot

### ISSUE THREAD

**Issue by JezaGaia** [TheIllusiveC4/CuriousElytra#6]
caelus-fabric-0.0.5-1.16.1
curios-fabric-1.16.1-0.3
curiouselytra-fabric-1.0.0-1.16.1
curioofundying-fabric-1.16.1-1.0
curiousshulkerboxes-fabric-1.16.1-1.0
fabric-api-0.16.0+build.384-1.16.1

I'm playing in Single player 1.16.1 with MultiMC loader and fabric
I have reproduced this bug consistently even when disabling any other mods and removing all datapacks.

When I have a mending elytra in the vanilla slot everything works as intended, I can loot XP no matter what I have in the new slots (shulker box and/or totem)
When I have a non enchanted elytra in the back slot everything works as intended (flying etc) and I can loot XP with no issue
When I have a mending **undamaged** elytra in the back slot everything works as intended (flying etc) and I can loot XP with no issue
When I use a **damaged** mending elytra in the back slot the game will freeze and crash as soon as there is XP to loot no matter if it comes from killing a mob or trading with a villager.

Here is the attached crash log
[crash-2020-07-16_01.42.36-server.txt](https://github.com/TheIllusiveC4/CuriousElytra/files/5022255/crash-2020-07-16_01.42.36-server.txt)

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
This should be fixed by Curios version 0.5.
