### ISSUE TITLE
Mending doesnt work

### ISSUE THREAD

**Issue by DuckXGG** [TheIllusiveC4/CuriousElytra#61]
* Elytra Slot: for fabric 1.19.2. Got it on better mc modpack

#### Observed Behavior:
Mending doesnt work when equiped in elytra slot
#### Expected Behavior:
mending working

**Comment by TheIllusiveC4** [comment]
Do you have Clumps installed? If so, is it updated to the latest version?

**Comment by DuckXGG** [comment]
Yes. I will update it now

søn. 25. dec. 2022 23.47 skrev C4 ***@***.***>:

**Comment by DuckXGG** [comment]
That worked thank you

**Comment by allanonmage** [comment]
What's a Clumps and where does one find it?
