### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by RobbyZzRobby** [TheIllusiveC4/CuriousElytra#65]
I would love to have mod support, for elytras with armor, alot of mods like better end and deeper darker have elytras that give armor I would love it if the mod allows you to equip them from other mods (and if they have to program that in) atleast make it so that is reads their armor stats and apply them

**Comment by TheIllusiveC4** [comment]
There's compatibility for BetterEnd and Deeper and Darker to place their elytras into the accessory slot; however, I do not plan to add their armor stats as well.
