### ISSUE TITLE
Compatibility with inventorio Mod Issue!

### ISSUE THREAD

**Issue by wilebaldo** [TheIllusiveC4/CuriousElytra#66]
The issue is very simple, when you have de Mod Inventorio, https://github.com/Lizard-Of-Oz/Inventorio
The extra slot for the elitras is gone, you can open to remove or add elitras. I dont know if this is a issue with this or the other mod.

**Comment by TheIllusiveC4** [comment]
I believe this is an issue with Inventorio as it's been reported it doesn't work with many mods that add extra inventory slots.
