### ISSUE TITLE
Compatibility with elytra rocket from quark.

### ISSUE THREAD

**Issue by KostromDan** [TheIllusiveC4/CuriousElytra#69]
Quark adds the ability to launch from the ground by right-clicking on a rocket into the air.
If the elytra is in the curio slot, it stops working. The Quark developer closed my problem without any comments, it looks like he doesn't want to fix it.
Video and more detailed description here.
https://github.com/VazkiiMods/Quark/issues/3935

**Comment by stlouisn** [comment]
you can close this as it was fixed in quark:

https://github.com/VazkiiMods/Quark/issues/4230
