### ISSUE TITLE
Elytra does not deploy

### ISSUE THREAD

**Issue by Avakining** [TheIllusiveC4/CuriousElytra#7]
#### Versions (Be specific, do not write "latest"):
* Curious Elytra: 1.16.1-3.0
* Caelus: 1.16.1-2.0-beta5
* Curios: 1.16.1-3.0.0.2
* Forge: 32.0.106

#### Steps to Reproduce:
1. Equip elytra in "Back" cuiro slot
2. Attempt to fly with elytra (jump while falling)
3. Instead, fall because elytra does not deploy

**Comment by TheIllusiveC4** [comment]
This is a Caelus issue. Try updating to the new 2.0-beta6 version, which should solve the issue.
