### ISSUE TITLE
Server Crash in Cottage Wtich modpack

### ISSUE THREAD

**Issue by VallenFrostweaver** [TheIllusiveC4/CuriousElytra#73]
* Elytra Slot: 6.1.0+ 1.19.2
* Caelus (Forge only): 3.0.0.6
* Forge 43.2.8

Crash Log: [Hastebin link](https://hastebin.com/share/merocajehe.php)
Using version 1.14.2 of Cottage Witch modpack on a server it causes a crash but in single player it's fine.

**Comment by TheIllusiveC4** [comment]
I think this is something that only occurs in certain environments, so it's hard for me to test my solution reliably. The new update should fix this in theory but let me know if this error persists and I'll re-open this.
