### ISSUE TITLE
[Bug]: Client crashes with Saving world/Incompatibilities with unknown mods. (Reported exception thrown! net.minecraft.class_148: Ticking entity)

### ISSUE THREAD

**Issue by whatamaniac** [TheIllusiveC4/CuriousElytra#76]
### Minecraft Version

1.19.2

### What happened?

When Joining Multiplayer Server Game Crashes with Saving World Screen with this Crash Report: https://pastebin.com/R2uLFgu2
This does not happen each and everytime but it does happen 6 out of 10 times either with my own profile or with my other players sending me this same report.
Here's the Latest Log: https://pastebin.com/7eqeBvWz

### How do you trigger this bug?

1. Join Multiplayer Server.
2. Move for a bit.
3. Saving World Screen and Crash.
...

### Loader

Fabric

### Loader Version

Fabric - 0.14.20

### API Version

fabric-api-0.76.0+1.19.2.jar

### Mod Version

elytraslot-fabric-6.1.1+1.19.2.jar

### Relevant Log Outputs

Crash Report: https://pastebin.com/R2uLFgu2
Latest Log: https://pastebin.com/7eqeBvWz

**Comment by TheIllusiveC4** [comment]
It looks like this is a result of a Roughly Enough Items bug that has since been addressed on that end. Updating to the latest version of that mod should fix this.
