### ISSUE TITLE
Fabric | Enchanted Elytra do not have enchanted glow on player model

### ISSUE THREAD

**Issue by FakeDomi** [TheIllusiveC4/CuriousElytra#8]
#### Versions (Be specific, do not write "latest"):
* Curious Elytra: 1.0.0-1.16.1
* Caelus: 0.0.6-1.16.1
* Curios: 1.16.1-0.5
* Fabric: 0.16.2+build.385-1.16.1
#### Observed Behavior:
Enchanted Elytra do not have the enchanted glow on the player model when equipped in the back slot.
#### Expected Behavior:
Glow should be rendered if the Elytra is enchanted.
#### Steps to Reproduce:
1. Enchant Elytra
2. Equip into back slot
3. Check in character preview or third-person view

**Comment by TheIllusiveC4** [comment]
This is a Caelus issue. I just pushed a v0.0.7 that should solve this.
