### ISSUE TITLE
[Bug]: Crash when equipping silent gear elytra

### ISSUE THREAD

**Issue by dmohr2** [TheIllusiveC4/CuriousElytra#84]
### Minecraft Version

1.20.1

### What happened?

Equipping a custom elytra from Silent Gear in the back slot crashes the client

### How do you trigger this bug?

1. Craft an elytra in silent gear
2. Equip it in the curios slot
3. Get disconnected from server

### Loader

Forge

### Loader Version

Forge 47.1.3

### API Version

N/A

### Mod Version

elytraslot=forge-6.3.0+1.20.1

**Comment by TheIllusiveC4** [comment]
I believe this is a Silent Gear bug that has since been fixed on their end.
