### ISSUE TITLE
[Feature]: add support for Enderite 

### ISSUE THREAD

**Issue by lieonlion** [TheIllusiveC4/CuriousElytra#88]
### What is the new feature or improvement?

could you add support for my Enderite?
I've been getting requests to add support, but be best if you did
Enderite Plated Elytra is only for 1.20.1 for now, but I will be releasing new versions and it would be in everything from 1.16.5 + (forge and fabric)

Modrinth - https://modrinth.com/mod/enderite-lieonlion
CurseForge - https://www.curseforge.com/minecraft/mc-mods/enderite-lieonlion

**Comment by LieOnLion** [comment]
oh and on CurseForge - https://www.curseforge.com/minecraft/mc-mods/enderite-lieonlion
