### ISSUE TITLE
[Bug]: Slot Will Not Open On Server

### ISSUE THREAD

**Issue by TheLegendofZoar** [TheIllusiveC4/CuriousElytra#89]
### Minecraft Version

1.20.1

### What happened?

Hi,

I recently added Elytra slot to a server I play on, and installed all the necessary APIs as seen on the mod page. In addition, I also have the mod installed on my device so I can use it for single player and because I believe it has to be active both server and client-side. 

The mod works great on single player and I have no issues. However, when I try to open the elytra slot on the server, the button color changes but no extra slot opens up. etc. 

Is there any way to fix this, or do you have anything I can do?

### How do you trigger this bug?

1. 
2.
3.
...

### Loader

Forge

### Loader Version

47.0.35

### Mod Version

Elytra Slot 6.3.0+1.20.1

**Comment by TheIllusiveC4** [comment]
When something like this occurs, this is usually a result of the slots on the server being configured differently than the slots on the client. Make sure that your mods are all the same (and that they are in fact installed on the server) and the configurations are all the same. This includes datapacks that could have modified the available slots on the server.

If none of these prove fruitful, there is the option to use the `/curios reset` command to reset the slots to their default configuration in the case that there was a runtime modification to the slots done on top of the default configuration.
