### ISSUE TITLE
[Bug]: Exit Code -1

### ISSUE THREAD

**Issue by Phoenix-warrior9** [TheIllusiveC4/CuriousElytra#90]
### Minecraft Version

1.19.2

### What happened?

I was trying to get a mod that would add another slot to my back for armor and backpacks and stuff, but this Imidiatly crashes my game on start. I don't even get to the start screen when I see exit code -1(crash logs below). 

### How do you trigger this bug?

1.Starting the game
2.
3.
...

### Loader

Forge

### Loader Version

Forge -43.2.3

### Mod Version

6.1.1+1.19.2

### Relevant Log Outputs

https://paste.gg/p/anonymous/d7cd2c0c3da6473b8156d5eb27f11616

**Comment by TheIllusiveC4** [comment]
The crash report doesn't show any errors from Elytra Slot. The errors are mainly from missing registry objects from other mods, although I'm not sure where the original source of those errors are coming from.
