### ISSUE TITLE
[Feature]: Compatibility with Clutter custom elytra

### ISSUE THREAD

**Issue by GeekyBakerBen** [TheIllusiveC4/CuriousElytra#91]
### What is the new feature or improvement?

I hate to pile onto the list (is it really not possible to just open this up to allow any modded elytra, at least through a config, rather than having to hardcode every single custom elytra in?! It feels crazy to have all this extra work on yourself...) but any chance this could update to allow the Butterfly elytra from the Clutter mod to work?

I had the slot operational with my basic elytra, but the second I updated it to one of the Clutter Butterfly elytra, it just won't operate anymore.

At first, it wouldn't go into the slot at all (presumably didn't recognise it even as an elytra). I then tried looking into your files and found the cape.json file where you had the hardcoding for things like the "lilwings" mod, and added the Clutter ones to that list. Now it at least allows me to place the custom elytra in the slot, but still won't activate it for flight.

MC version 1.20.1 Fabric
Elytraslot version 6.3.0

**Comment by TheIllusiveC4** [comment]
> (is it really not possible to just open this up to allow any modded elytra, at least through a config, rather than having to hardcode every single custom elytra in?! It feels crazy to have all this extra work on yourself...)

There are many reasons that it's currently as restrictive as it is, mostly because elytras aren't as standardized as you might think. They can functionally be very different and it's hard to accommodate for all of them smoothly, opening it up in such a manner has caused a couple issues in the past that led to the current state. 

That said, by no means is the current implementation ideal and I have had ideas to make the experience better for allowing custom elytras more easily but I just haven't had time to implement it yet because it requires basically a top-down rewrite of the whole compatibility logic in this mod.

**Comment by GeekyBakerBen** [comment]
> > (is it really not possible to just open this up to allow any modded elytra, at least through a config, rather than having to hardcode every single custom elytra in?! It feels crazy to have all this extra work on yourself...)
> 
> There are many reasons that it's currently as restrictive as it is, mostly because elytras aren't as standardized as you might think. They can functionally be very different and it's hard to accommodate for all of them smoothly, opening it up in such a manner has caused a couple issues in the past that led to the current state.
> 
> That said, by no means is the current implementation ideal and I have had ideas to make the experience better for allowing custom elytras more easily but I just haven't had time to implement it yet because it requires basically a top-down rewrite of the whole compatibility logic in this mod.

That makes sense then. I've never tried making my own mod so I'm very in awe of what you manage to do, especially maintaining many versions etc. I wish it could be easier on you, as I hate to think how stressful it must get to have people on your back about it :/

**Comment by TheIllusiveC4** [comment]
It seems like Trinkets compatibility with Clutter's elytra has been added on their end.
