### ISSUE TITLE
[Feature]: Mention that Caelus API is needed on the mod page

### ISSUE THREAD

**Issue by Catoumy** [TheIllusiveC4/CuriousElytra#93]
### What is the new feature or improvement?

After 30 minutes of back and forth trying to figure out why the elytraslot mod was crashing my server
i find out after opening minecraft and trying to join the server with the mod DISABLED on both server and client
that Caelus API was also downloaded on my client without me knowing (curseforge app).

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/illusivesoulworks/elytraslot/issues/80
