### ISSUE TITLE
that the elitras slot mod is compatible with fltpot-1.20.1-0.3.0

### ISSUE THREAD

**Issue by yHenriTopper** [TheIllusiveC4/CuriousElytra#98]
### What is the new feature or improvement?

I suppose the same thing must happen here, the elytras cannot be put in the elytras slot because the mod fltpot-1.20.1-0.3.0 adds an item similar to the elytras, they are not elytras, but there will be some way that they are compatible? Or would it be better to wait for the creator of the fltpot-1.20.1-0.3.0 mod to make it possible?

**Comment by TheIllusiveC4** [comment]
The wings from that mod are different enough from elytras that it would be best for them to code their own integration for Curios/Trinkets.
