### ISSUE TITLE
[Bug]: The game crashes when placing the elytra in the back slot

### ISSUE THREAD

**Issue by ArthuzimCode** [TheIllusiveC4/CuriousElytra#99]
### Minecraft Version

1.16.5

### What happened?

Even using the APIs for this version, when trying to place the elytra in the back slot, the game freezes forever and sometimes crashes

### How do you trigger this bug?

1. I dragged the mod and the APIs (caelus, curios) to the minecraft mods folder
2.the game starts normally, and the slot appears in the inventory
3. When trying to place any item, the game freezes or crashes
...

### Loader

Forge

### Loader Version

Forge 36.2.39

### API Version

Forge (I dont know xD)

### Mod Version

curiouselytra-forge-1.16.5-4.0.2.4

**Comment by TheIllusiveC4** [comment]
Please attach the relevant crash log.
